user-message: "WARNING: This stack project is generated."

ghc-options:
  "$locals": -fhide-source-paths
  futhark: -j -fwrite-ide-info -hiedir=.hie

resolver: nightly-2023-11-25

# We have 1 package.
packages:
  - ./.

extra-deps:
  # Package versions for published packages either not on Stackage or
  # not matching the version on Stackage for the resolver we use.
  # These package-version extra dependencies are equivalent to cabal constraints.
  - fgl-visualize-0.1.0.1
  - futhark-data-1.1.0.1
  - futhark-manifest-1.2.0.1
  - futhark-server-1.2.2.1
