user-message: "WARNING: This stack project is generated."

ghc-options:
  "$locals": -fhide-source-paths
  futhark: -j -fwrite-ide-info -hiedir=.hie

resolver: nightly-2023-11-25

# We have 1 packages.
packages:
  - ./.

# We have 0 source packages listed in this order:
#   * external 0
#   * internal 0
#   * external forks 0
#   * internal forks 0
extra-deps:

  # Source Packages, external (3rd party).

  # Source Packages, internal to this organisation (private and public).

  # Source Packages, external (3rd party) forks of other repositories.
  # Can we help upstream?

  # Source Packages, internal forks of other repositories.
  # Can we upstream and unfork?

  # Package versions for published packages either not on Stackage or
  # not matching the version on Stackage for the resolver we use.
  # These package-version extra dependencies are equivalent to cabal constraints.
  - fgl-visualize-0.1.0.1
  - futhark-data-1.1.0.1
  - futhark-manifest-1.2.0.1
  - futhark-server-1.2.2.1
