[ { dep = "fgl-visualize", ver = "0.1.0.1" }
, { dep = "futhark-data", ver = "1.1.0.1" }
, { dep = "futhark-manifest", ver = "1.2.0.1" }
, { dep = "futhark-server", ver = "1.2.2.1" }
-- 1st group of recommendations
, { dep = "Diff", ver ="0.5" }
, { dep = "aeson", ver ="2.2.1.0" }
, { dep = "alex", ver ="3.4.0.1" }
, { dep = "ansi-terminal", ver ="1.0" }
, { dep = "base16-bytestring", ver ="1.0.2.0" }
, { dep = "blaze-html", ver ="0.9.1.2" }
, { dep = "bmp", ver ="1.2.6.3" }
, { dep = "bytestring-to-vector", ver ="0.3.0.1" }
, { dep = "cmark-gfm", ver ="0.2.6" }
, { dep = "co-log-core", ver ="0.3.2.1" }
, { dep = "cryptohash-md5", ver ="0.11.101.0" }
, { dep = "directory-tree", ver ="0.12.1" }
, { dep = "dlist", ver ="1.0" }
, { dep = "dotgen", ver ="0.4.3" }
, { dep = "fgl", ver ="5.8.2.0" }
, { dep = "file-embed", ver ="0.0.15.0" }
, { dep = "free", ver ="5.2" }
, { dep = "githash", ver ="0.1.7.0" }
, { dep = "half", ver ="0.3.1" }
, { dep = "happy", ver ="1.20.1.1" }
, { dep = "language-c-quote", ver ="0.13.0.1" }
, { dep = "lens", ver ="5.2.3" }
, { dep = "lsp", ver ="2.3.0.0" }
, { dep = "lsp-types", ver ="2.1.0.0" }
, { dep = "mainland-pretty", ver ="0.7.1" }
, { dep = "megaparsec", ver ="9.6.1" }
, { dep = "mwc-random", ver ="0.15.0.2" }
, { dep = "neat-interpolation", ver ="0.5.1.4" }
, { dep = "parallel", ver ="3.2.2.0" }
, { dep = "prettyprinter", ver ="1.7.1" }
, { dep = "prettyprinter-ansi-terminal", ver ="1.1.3" }
, { dep = "process-extras", ver ="0.7.4" }
, { dep = "random", ver ="1.2.1.1" }
, { dep = "regex-tdfa", ver ="1.3.2.2" }
, { dep = "scientific", ver ="0.3.7.0" }
, { dep = "srcloc", ver ="0.6.0.1" }
, { dep = "statistics", ver ="0.16.2.1" }
, { dep = "temporary", ver ="1.3" }
, { dep = "terminal-size", ver ="0.3.4" }
, { dep = "vector", ver ="0.13.1.0" }
, { dep = "vector-binary-instances", ver ="0.2.5.2" }
, { dep = "versions", ver ="6.0.3" }
, { dep = "zlib", ver ="0.6.3.0" }
-- 2nd group of recommendations
, { dep = "ListLike", ver ="4.7.8.2" }
, { dep = "OneTuple", ver ="0.4.1.1" }
, { dep = "QuickCheck", ver ="2.14.3" }
, { dep = "ansi-terminal-types", ver ="0.11.5" }
, { dep = "assoc", ver ="1.1" }
, { dep = "async", ver ="2.2.4" }
, { dep = "attoparsec", ver ="0.14.4" }
, { dep = "base-orphans", ver ="0.9.1" }
, { dep = "bifunctors", ver ="5.6.1" }
, { dep = "blaze-builder", ver ="0.4.2.3" }
, { dep = "blaze-markup", ver ="0.8.3.0" }
, { dep = "call-stack", ver ="0.4.0" }
, { dep = "case-insensitive", ver ="1.2.1.0" }
, { dep = "colour", ver ="2.3.6" }
, { dep = "comonad", ver ="5.0.8" }
, { dep = "contravariant", ver ="1.5.5" }
, { dep = "data-default", ver ="0.7.1.1" }
, { dep = "data-default-class", ver ="0.1.2.0" }
, { dep = "data-fix", ver ="0.3.2" }
, { dep = "dense-linear-algebra", ver ="0.1.0.0" }
, { dep = "distributive", ver ="0.6.2.1" }
, { dep = "exception-mtl", ver ="0.4.0.2" }
, { dep = "exception-transformers", ver ="0.4.0.12" }
, { dep = "generic-deriving", ver ="1.14.5" }
, { dep = "generically", ver ="0.1.1" }
, { dep = "hashable", ver ="1.4.3.0" }
, { dep = "haskell-src-meta", ver ="0.8.13" }
, { dep = "indexed-traversable", ver ="0.1.3" }
, { dep = "indexed-traversable-instances", ver ="0.1.1.2" }
, { dep = "integer-conversion", ver ="0.1.0.1" }
, { dep = "integer-logarithms", ver ="1.0.3.1" }
, { dep = "kan-extensions", ver ="5.2.5" }
, { dep = "lens-aeson", ver ="1.2.3" }
, { dep = "math-functions", ver ="0.3.4.3" }
, { dep = "mod", ver ="0.2.0.1" }
, { dep = "network-uri", ver ="2.6.4.2" }
, { dep = "parser-combinators", ver ="1.3.0" }
, { dep = "primitive", ver ="0.9.0.0" }
, { dep = "profunctors", ver ="5.6.2" }
, { dep = "reflection", ver ="2.1.7" }
, { dep = "regex", ver ="1.1.0.2" }
, { dep = "regex-base", ver ="0.94.0.2" }
, { dep = "row-types", ver ="1.0.1.2" }
, { dep = "safe", ver ="0.3.19" }
, { dep = "semialign", ver ="1.3" }
, { dep = "semigroupoids", ver ="6.0.0.1" }
, { dep = "some", ver ="1.0.6" }
, { dep = "sorted-list", ver ="0.2.2.0" }
, { dep = "splitmix", ver ="0.1.0.5" }
, { dep = "strict", ver ="0.5" }
, { dep = "syb", ver ="0.7.2.4" }
, { dep = "tagged", ver ="0.8.8" }
, { dep = "text-iso8601", ver ="0.1" }
, { dep = "text-rope", ver ="0.2" }
, { dep = "text-short", ver ="0.1.5" }
, { dep = "th-abstraction", ver ="0.6.0.0" }
, { dep = "th-compat", ver ="0.1.4" }
, { dep = "these", ver ="1.2" }
, { dep = "time-compat", ver ="1.9.6.1" }
, { dep = "transformers-base", ver ="0.4.6" }
, { dep = "transformers-compat", ver ="0.7.2" }
, { dep = "unliftio-core", ver ="0.2.1.0" }
, { dep = "unordered-containers", ver ="0.2.19.1" }
, { dep = "uuid", ver ="1.3.15" }
, { dep = "uuid-types", ver ="1.0.5.1" }
, { dep = "vector-algorithms", ver ="0.9.0.1" }
, { dep = "vector-stream", ver ="0.1.0.0" }
, { dep = "vector-th-unbox", ver ="0.2.2" }
, { dep = "witherable", ver ="0.4.2" }
-- 3rd group of recommendations
, { dep = "StateVar", ver ="1.2.2" }
, { dep = "adjunctions", ver ="4.4.2" }
, { dep = "base-compat", ver ="0.13.1" }
, { dep = "bitvec", ver ="1.1.5.0" }
, { dep = "constraints", ver ="0.14" }
, { dep = "cryptohash-sha1", ver ="0.11.101.0" }
, { dep = "data-default-instances-containers", ver ="0.0.1" }
, { dep = "data-default-instances-dlist", ver ="0.0.1" }
, { dep = "data-default-instances-old-locale", ver ="0.0.1" }
, { dep = "entropy", ver ="0.4.1.10" }
, { dep = "fail", ver ="4.9.0.0" }
, { dep = "fmlist", ver ="0.9.4" }
, { dep = "generic-lens", ver ="2.2.2.0" }
, { dep = "haskell-src-exts", ver ="1.23.1" }
, { dep = "invariant", ver ="0.6.2" }
, { dep = "network-info", ver ="0.2.1" }
, { dep = "regex-pcre-builtin", ver ="0.95.2.3.8.44" }
, { dep = "semirings", ver ="0.6" }
, { dep = "th-orphans", ver ="0.13.14" }
, { dep = "time-locale-compat", ver ="0.1.1.5" }
, { dep = "utf8-string", ver ="1.0.2" }
-- 4th group of recommendations
, { dep = "base-compat-batteries", ver ="0.13.1" }
, { dep = "boring", ver ="0.2.1" }
, { dep = "generic-lens-core", ver ="2.2.1.0" }
, { dep = "old-locale", ver ="1.0.0.7" }
, { dep = "semigroups", ver ="0.20" }
, { dep = "th-lift", ver ="0.8.4" }
, { dep = "th-reify-many", ver ="0.1.10" }
, { dep = "type-equality", ver ="1" }
, { dep = "void", ver ="0.7.3" }
-- 5th group of recommendations
, { dep = "indexed-profunctors", ver ="0.1.1.1" }
, { dep = "th-expand-syns", ver ="0.4.11.0" }
-- 6th group of recommendations
, { dep = "tasty", ver ="1.5" }
, { dep = "tasty-hunit", ver ="0.10.1" }
, { dep = "tasty-quickcheck", ver ="0.10.3" }
-- 7th group of recommendations
, { dep = "optparse-applicative", ver = "0.18.1.0" }
]
